baseURL: https://www.kainonly.com
title: Web åº”ç”¨æŠ€æœ¯åˆ†äº«
defaultContentLanguage: zh
paginate: 5
theme: PaperMod

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - JSON

params:
  assets:
    favicon: favicon.png
  homeInfoParams:
    Title: ğŸ‘‹ Hi, there. I'm Kain
    Content: å…¨æ ˆå·¥ç¨‹å¸ˆ & DevOps
  socialIcons:
    - name: github
      url: https://github.com/kainonly
    - name: stackoverflow
      url: https://stackoverflow.com/users/10020012/kain
    - name: email
      url: mailto:work@kainonly.com
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title" ]

menu:
  main:
    - identifier: search
      name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: weplanx
      name: WEPLANX
      url: https://weplanx.gitbook.io
      weight: 40


markup:
  highlight:
    noClasses: false
    style: github

googleAnalytics: G-J0NVPEBDTM
copyright: "[ç¼ ICP å¤‡ 18004473 å·](https://beian.miit.gov.cn)"

